#!/usr/bin/env bash

if
  [[ -s "/home/ec2-user/.rvm/gems/ruby-2.0.0-p648@global/environment" ]]
then
  source "/home/ec2-user/.rvm/gems/ruby-2.0.0-p648@global/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ec2-user/.rvm/gems/ruby-2.0.0-p648@global/environment'" >&2
  exit 1
fi
