# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e33c8895f7939fa436efa610e3cfbea5400560ed951759aaadb5fbbb193b37f4e762919203fefb8adcbbc6565973895a3fe4b3f27216ba8adf5164b6a57ebbc

test:
  secret_key_base: 1b4705e23483f0e59bc214d3273b030e34f54740d1f49a015e355041b3f788cd2cbb96639ff7c736fb9b2220cf2847d500258969671a6a01407e10464e36dbaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
