#!/usr/bin/env bash

if
  [[ -s "/home/ec2-user/.rvm/gems/ruby-2.2.4/environment" ]]
then
  source "/home/ec2-user/.rvm/gems/ruby-2.2.4/environment"
  exec passenger-install-nginx-module "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ec2-user/.rvm/gems/ruby-2.2.4/environment'" >&2
  exit 1
fi
