#!/usr/bin/env bash

if
  [[ -s "/home/ec2-user/.rvm/gems/jruby-9.0.5.0/environment" ]]
then
  source "/home/ec2-user/.rvm/gems/jruby-9.0.5.0/environment"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ec2-user/.rvm/gems/jruby-9.0.5.0/environment'" >&2
  exit 1
fi
